/**
 * FilesPage - Workspace files overview
 *
 * Shows files organized by type:
 * - Created: Artifacts generated by the AI (code, documents, apps)
 * - Uploaded: Files attached by the user to conversations
 */

import * as React from 'react'
import { useMemo } from 'react'
import { useAtomValue } from 'jotai'
import { formatDistanceToNow } from 'date-fns'
import {
  FileCode,
  FileText,
  Globe,
  Table,
  GitBranch,
  Image,
  File,
  Paperclip,
  ExternalLink,
  Sparkles,
  Upload,
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { PanelHeader } from '@/components/app-shell/PanelHeader'
import { ScrollArea } from '@/components/ui/scroll-area'
import { sessionIdsAtom, sessionMetaMapAtom, sessionAtomFamily } from '@/atoms/sessions'
import { sessionArtifactsAtomFamily } from '@/atoms/artifacts'
import { navigate, routes } from '@/lib/navigate'
import type { AnyArtifact, ArtifactType, StoredAttachment } from '../../shared/types'

// =============================================================================
// Types
// =============================================================================

interface AggregatedArtifact extends AnyArtifact {
  sessionName?: string
}

interface AggregatedAttachment extends StoredAttachment {
  sessionId: string
  sessionName?: string
  timestamp: number
}

// =============================================================================
// Helper Components
// =============================================================================

function SectionHeader({
  title,
  count,
  icon: Icon,
}: {
  title: string
  count?: number
  icon: React.ComponentType<{ className?: string }>
}) {
  return (
    <div className="flex items-center gap-2 mb-3 mt-6 first:mt-0">
      <Icon className="h-3.5 w-3.5 text-foreground/30" />
      <h2 className="text-[11px] font-semibold uppercase tracking-wider text-foreground/40">
        {title}
      </h2>
      {count !== undefined && count > 0 && (
        <span className="text-[10px] text-foreground/30 bg-foreground/5 rounded-full px-1.5 py-0.5 tabular-nums">
          {count}
        </span>
      )}
    </div>
  )
}

function EmptyState({
  icon: Icon,
  title,
  description
}: {
  icon: React.ComponentType<{ className?: string }>
  title: string
  description: string
}) {
  return (
    <div className="flex flex-col items-center justify-center py-8 px-4 text-center">
      <div className="h-10 w-10 rounded-full bg-foreground/[0.03] flex items-center justify-center mb-3">
        <Icon className="h-5 w-5 text-foreground/20" />
      </div>
      <p className="text-[13px] font-medium text-foreground/50 mb-1">{title}</p>
      <p className="text-[11px] text-foreground/30 max-w-[240px]">{description}</p>
    </div>
  )
}

// =============================================================================
// Artifact Helpers
// =============================================================================

function getArtifactIcon(type: ArtifactType) {
  const iconClass = "h-4 w-4"
  switch (type) {
    case 'html':
      return <Globe className={iconClass} />
    case 'document':
      return <FileText className={iconClass} />
    case 'spreadsheet':
      return <Table className={iconClass} />
    case 'code':
      return <FileCode className={iconClass} />
    case 'diagram':
      return <GitBranch className={iconClass} />
    default:
      return <File className={iconClass} />
  }
}

function getArtifactTypeLabel(type: ArtifactType): string {
  switch (type) {
    case 'html':
      return 'Web App'
    case 'document':
      return 'Document'
    case 'spreadsheet':
      return 'Spreadsheet'
    case 'code':
      return 'Code'
    case 'diagram':
      return 'Diagram'
    default:
      return 'File'
  }
}

function getArtifactColor(type: ArtifactType): string {
  switch (type) {
    case 'html':
      return 'text-blue-500 bg-blue-500/10'
    case 'document':
      return 'text-amber-500 bg-amber-500/10'
    case 'spreadsheet':
      return 'text-emerald-500 bg-emerald-500/10'
    case 'code':
      return 'text-violet-500 bg-violet-500/10'
    case 'diagram':
      return 'text-pink-500 bg-pink-500/10'
    default:
      return 'text-foreground/50 bg-foreground/5'
  }
}

// =============================================================================
// File Card Components
// =============================================================================

interface ArtifactCardProps {
  artifact: AggregatedArtifact
  onClick?: () => void
}

function ArtifactCard({ artifact, onClick }: ArtifactCardProps) {
  const colorClass = getArtifactColor(artifact.type)

  return (
    <button
      onClick={onClick}
      className={cn(
        "group relative flex flex-col p-4 rounded-xl border border-foreground/[0.06]",
        "bg-foreground/[0.015] hover:bg-foreground/[0.03] hover:border-foreground/10",
        "transition-all duration-150 text-left w-full",
        "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
      )}
    >
      {/* Icon & Type Badge */}
      <div className="flex items-start justify-between mb-3">
        <div className={cn("h-9 w-9 rounded-lg flex items-center justify-center", colorClass)}>
          {getArtifactIcon(artifact.type)}
        </div>
        <span className="text-[10px] font-medium text-foreground/30 uppercase tracking-wide">
          {getArtifactTypeLabel(artifact.type)}
        </span>
      </div>

      {/* Title */}
      <h3 className="text-[13px] font-medium text-foreground mb-1 line-clamp-2 leading-snug">
        {artifact.title}
      </h3>

      {/* Metadata */}
      <div className="flex items-center gap-2 mt-auto pt-2">
        {artifact.sessionName && (
          <span className="text-[11px] text-foreground/30 truncate max-w-[120px]">
            {artifact.sessionName}
          </span>
        )}
        <span className="text-[11px] text-foreground/20">
          {formatDistanceToNow(artifact.updatedAt, { addSuffix: true })}
        </span>
      </div>

      {/* Hover indicator */}
      <div className="absolute top-3 right-3 opacity-0 group-hover:opacity-100 transition-opacity">
        <ExternalLink className="h-3.5 w-3.5 text-foreground/30" />
      </div>
    </button>
  )
}

interface UploadedFileCardProps {
  file: AggregatedAttachment
  onClick?: () => void
}

function UploadedFileCard({ file, onClick }: UploadedFileCardProps) {
  const isImage = file.mimeType.startsWith('image/')
  const isPdf = file.mimeType === 'application/pdf'

  const formatSize = (bytes: number) => {
    if (bytes < 1024) return `${bytes} B`
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
  }

  return (
    <button
      onClick={onClick}
      className={cn(
        "group flex items-center gap-3 p-3 rounded-lg",
        "hover:bg-foreground/[0.03] transition-colors w-full text-left",
        "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
      )}
    >
      {/* Icon */}
      <div className={cn(
        "h-10 w-10 rounded-lg flex items-center justify-center shrink-0",
        isImage ? "text-pink-500 bg-pink-500/10" :
        isPdf ? "text-red-500 bg-red-500/10" :
        "text-foreground/40 bg-foreground/5"
      )}>
        {isImage ? <Image className="h-4 w-4" /> :
         isPdf ? <FileText className="h-4 w-4" /> :
         <Paperclip className="h-4 w-4" />}
      </div>

      {/* Info */}
      <div className="flex-1 min-w-0">
        <p className="text-[13px] font-medium text-foreground truncate">{file.name}</p>
        <div className="flex items-center gap-2 text-[11px] text-foreground/40">
          <span>{formatSize(file.size)}</span>
          {file.sessionName && (
            <>
              <span className="text-foreground/20">·</span>
              <span className="truncate">{file.sessionName}</span>
            </>
          )}
        </div>
      </div>

      {/* Timestamp */}
      <span className="text-[11px] text-foreground/30 shrink-0">
        {formatDistanceToNow(file.timestamp, { addSuffix: true })}
      </span>
    </button>
  )
}

// =============================================================================
// Custom Hook: Aggregate Artifacts
// =============================================================================

function useAllArtifacts(): AggregatedArtifact[] {
  const sessionIds = useAtomValue(sessionIdsAtom)
  const sessionMetaMap = useAtomValue(sessionMetaMapAtom)

  // Read artifacts for each session
  // Note: We need to read each session's artifacts atom individually
  const artifactsBySession = sessionIds.map(sessionId => {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const artifacts = useAtomValue(sessionArtifactsAtomFamily(sessionId))
    return { sessionId, artifacts }
  })

  return useMemo(() => {
    const allArtifacts: AggregatedArtifact[] = []

    for (const { sessionId, artifacts } of artifactsBySession) {
      const meta = sessionMetaMap.get(sessionId)
      for (const artifact of artifacts) {
        allArtifacts.push({
          ...artifact,
          sessionName: meta?.name || meta?.preview?.slice(0, 30),
        })
      }
    }

    // Sort by most recently updated
    return allArtifacts.sort((a, b) => b.updatedAt - a.updatedAt)
  }, [artifactsBySession, sessionMetaMap])
}

// =============================================================================
// Custom Hook: Aggregate Attachments
// =============================================================================

function useAllAttachments(): AggregatedAttachment[] {
  const sessionIds = useAtomValue(sessionIdsAtom)
  const sessionMetaMap = useAtomValue(sessionMetaMapAtom)

  // Read each session to get messages with attachments
  const sessionData = sessionIds.map(sessionId => {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const session = useAtomValue(sessionAtomFamily(sessionId))
    return { sessionId, session }
  })

  return useMemo(() => {
    const allAttachments: AggregatedAttachment[] = []

    for (const { sessionId, session } of sessionData) {
      if (!session?.messages) continue

      const meta = sessionMetaMap.get(sessionId)
      const sessionName = meta?.name || meta?.preview?.slice(0, 30)

      for (const message of session.messages) {
        if (message.role === 'user' && message.attachments) {
          for (const attachment of message.attachments) {
            allAttachments.push({
              ...attachment,
              sessionId,
              sessionName,
              timestamp: message.timestamp,
            })
          }
        }
      }
    }

    // Sort by most recent
    return allAttachments.sort((a, b) => b.timestamp - a.timestamp)
  }, [sessionData, sessionMetaMap])
}

// =============================================================================
// Main Component
// =============================================================================

export default function FilesPage() {
  const artifacts = useAllArtifacts()
  const attachments = useAllAttachments()

  const handleArtifactClick = (artifact: AggregatedArtifact) => {
    // Navigate to the session's canvas view
    navigate(routes.view.chat(artifact.sessionId))
  }

  const handleAttachmentClick = (file: AggregatedAttachment) => {
    // Open the file in the default app
    if (file.storedPath) {
      window.electronAPI.openFile(file.storedPath)
    }
  }

  return (
    <div className="flex flex-col h-full">
      <PanelHeader title="Files" />

      <ScrollArea className="flex-1 min-h-0">
        <div className="px-4 pb-6 pt-2">
          {/* Created Section */}
          <SectionHeader title="Created" count={artifacts.length} icon={Sparkles} />

          {artifacts.length === 0 ? (
            <EmptyState
              icon={Sparkles}
              title="No created files yet"
              description="Files generated by the AI during conversations will appear here"
            />
          ) : (
            <div className="grid grid-cols-2 gap-3">
              {artifacts.map((artifact) => (
                <ArtifactCard
                  key={artifact.id}
                  artifact={artifact}
                  onClick={() => handleArtifactClick(artifact)}
                />
              ))}
            </div>
          )}

          {/* Uploaded Section */}
          <SectionHeader title="Uploaded" count={attachments.length} icon={Upload} />

          {attachments.length === 0 ? (
            <EmptyState
              icon={Upload}
              title="No uploaded files yet"
              description="Files you attach to messages will appear here"
            />
          ) : (
            <div className="flex flex-col">
              {attachments.map((file) => (
                <UploadedFileCard
                  key={`${file.sessionId}-${file.id}`}
                  file={file}
                  onClick={() => handleAttachmentClick(file)}
                />
              ))}
            </div>
          )}
        </div>
      </ScrollArea>
    </div>
  )
}
